#!/usr/bin/env python
"""Decompose the numerator rep of sector {0,1,2,3}'s symmetry group and exhibit the
irreducible block. Burnside: d x d matrices act absolutely irreducibly iff the algebra
they generate is all of M_d (dimension d^2). We find the smallest invariant subspace
and test irreducibility -> shows there is NO single lex representative it reduces to."""
import sys, os, itertools
BASE="/het/p4/dshih/jet_images-deep_learning/SAILIR_phase2"
sys.path.insert(0,BASE); sys.path.insert(0,os.path.join(BASE,"reduction"))
from sailir import ibp_env
from sailir.topology import Topology
ibp_env.init_from_topology(Topology.from_dir(os.path.join(BASE,"topology_input/pentagonbox_nosym"))); ibp_env.set_prime(1009)
from canonicalize import _transforms, image_unsigned
P=1009; ND=8
def sec(i): return tuple(1 if i[k]>0 else 0 for k in range(ND))
def inv(a): return pow(a,P-2,P)
corner=(1,1,1,1,0,0,0,0,0,0,0); S=(0,1,2,3)
slots=[j for j in range(ND) if j not in S]+[8,9,10]
B=[tuple(-1 if k==j else corner[k] for k in range(11)) for j in slots]
Bi={b:i for i,b in enumerate(B)}; n=len(B)
csec=sec(corner)
def proj_action(t):
    M=[[0]*n for _ in range(n)]
    for j,b in enumerate(B):
        img=image_unsigned(b,*t)
        if img is None: continue
        for k,co in img.items():
            if k in Bi: M[Bi[k]][j]=co%P
    return M
autos=[t for t in _transforms(corner) if (lambda im: im and len(im)==1 and sec(next(iter(im)))==csec)(image_unsigned(corner,*t))]
GENS=[proj_action(t) for t in autos]

def mv(M,v,dim): return [sum(M[i][k]*v[k] for k in range(dim))%P for i in range(dim)]
def mm(A,Bm,dim): return [[sum(A[i][k]*Bm[k][j] for k in range(dim))%P for j in range(dim)] for i in range(dim)]
def rref(rows,w):
    rows=[r[:] for r in rows]; piv=[]; r=0
    for c in range(w):
        p=next((i for i in range(r,len(rows)) if rows[i][c]%P),None)
        if p is None: continue
        rows[r],rows[p]=rows[p],rows[r]; iv=inv(rows[r][c]); rows[r]=[(x*iv)%P for x in rows[r]]
        for i in range(len(rows)):
            if i!=r and rows[i][c]%P:
                f=rows[i][c]; rows[i]=[(rows[i][j]-f*rows[r][j])%P for j in range(w)]
        piv.append(c); r+=1
        if r==len(rows): break
    return rows[:r],piv
def dimspan(vs,w): return len(rref(vs,w)[0])
def inv_span(seed):
    basis=[seed[:]]; fr=[seed[:]]
    while fr:
        v=fr.pop()
        for g in GENS:
            w=mv(g,v,n)
            if dimspan(basis+[w],n)>dimspan(basis,n): basis.append(w); fr.append(w)
        if len(basis)>=n: break
    red,_=rref(basis,n); return red

# ---- search minimal invariant subspace over many seeds ----
seeds=[]
for j in range(n): seeds.append([1 if k==j else 0 for k in range(n)])
for i in range(n):
    for j in range(i+1,n):
        for s in (1,P-1):
            v=[0]*n; v[i]=1; v[j]=s; seeds.append(v)
best=None
for sd in seeds:
    W=inv_span(sd)
    if len(W)>=2 and (best is None or len(W)<len(best)): best=W
# collect all distinct minimal dims
dims=sorted({len(inv_span(sd)) for sd in seeds})
print(f"sector {S}: numerator rep dim {n}, slots {slots}")
print(f"distinct invariant-subspace dims from seeds: {dims}")
minW=best
print(f"smallest invariant subspace found: dim {len(minW)}")

# restrict GENS to minW and Burnside-test irreducibility
d=len(minW); red,piv=rref(minW,n)
def coords(vecn):  # express length-n vector in minW basis (RREF, pivot readoff)
    c=[0]*d; tmp=vecn[:]
    for b,pc in enumerate(piv):
        c[b]=tmp[pc]%P; tmp=[(tmp[k]-c[b]*red[b][k])%P for k in range(n)]
    return None if any(x%P for x in tmp) else c
def restrict(g):
    R=[[0]*d for _ in range(d)]
    for a in range(d):
        gc=coords(mv(g,red[a],n))
        if gc is None: return None
        for b in range(d): R[b][a]=gc[b]
    return R
rest=[R for R in (restrict(g) for g in GENS) if R is not None]
idD=[[1 if i==j else 0 for j in range(d)] for i in range(d)]
nontriv=[R for R in rest if R!=idD]
comm=all(mm(a,b,d)==mm(b,a,d) for a in nontriv for b in nontriv)
# Burnside: algebra generated by rest (+ identity) inside M_d (d^2-dim)
def flat(M): return tuple(M[i][j] for i in range(d) for j in range(d))
algo=[idD]+nontriv; algset=[flat(idD)]+[flat(R) for R in nontriv]
changed=True
while changed:
    changed=False
    cur=[list(x) for x in algset]
    for x in list(algo):
        for g in nontriv:
            pr=mm(x,g,d)
            if dimspan(cur+[flat(pr)],d*d)>dimspan(cur,d*d):
                algo.append(pr); algset.append(flat(pr)); cur.append(list(flat(pr))); changed=True
algdim=dimspan(algset,d*d)
print(f"\nsmallest invariant block: dim d={d}")
print(f"  restricted generators commute? {comm}")
print(f"  Burnside algebra dim = {algdim}  (=d^2={d*d} means ABSOLUTELY IRREDUCIBLE)")
print("  VERDICT:", "IRREDUCIBLE >=2D block -> no lex representative; cannot triangularize"
      if algdim==d*d and d>=2 else ("1D (reduces cleanly)" if d==1 else "reducible - peel further"))
print("\n  block basis vectors (as numerator combinations over slots %s):"%slots)
def show(v): return " + ".join(f"{c%P}*num@{slots[i]}" for i,c in enumerate(v) if c%P)
for row in red: print("     ",show(row))
print("\n  explicit d x d generator matrices on this block:")
for idx,R in enumerate(nontriv):
    print(f"    g{idx}:")
    for r in R: print("       ",r)
