#!/usr/bin/env python
"""TRUTH ENGINE — model-free ground-truth reductions and trajectories.

A classical Laporta-style elimination done in OUR sector-senior total order:
every equation in the system is generated by exactly one (operator, seed)
pair — i.e. one beam-search ACTION — so the elimination record doubles as a
GROUND-TRUTH REDUCTION TRAJECTORY in the worker's exact action space:

  per SECTOR SYSTEM (sector cone, seed caps r<=rmax, s<=smax):
    1. generate every IBP+LI equation from every in-sector seed in the box
    2. forward-eliminate over GF(p), processing equations lowest-max first,
       pivoting each reduced equation on its MAX integral in the total order;
       store  rules[pivot] = (tail, op, seed)   (tail strictly lower)
    3. equations whose reduced pivot is a MASTER are skipped (standard
       Laporta: they become trivial once the system is complete; at finite
       caps their tails may simply lack rules). Correctness is gated at the
       END by exact agreement with the FIRE oracle, not per equation.

  REPLAY from a target T (the truth trajectory):
    expr = {T: 1}; repeatedly take the HIGHEST-in-order non-master J in expr
    (the worker's maxweight pivot selection), apply its rule (recorded action
    (J, op, seed-J)), substitute. Sector systems for subsector debris are
    built on demand (recursion); Kira's trivialsector list short-circuits
    scaleless sectors to 0. Terminates when only masters remain.

  Outputs: the exact master-basis answer (gate: must equal the FIRE oracle
  for table targets) and the full trajectory [(state, action), ...] — truth
  data for model diagnosis and fine-tuning.

Usage:
  SAILIR_TOPOLOGY=... SAILIR_SECTOR_RANK=1 truth_engine.py \
      --integral 1,1,1,1,1,1,1,0,0,-1,-1,0,0,0,0 --output out.pkl \
      [--dr 1 --ds 1]     seed caps: r(T)+dr, s(T)+ds per sector system
"""
import os, sys, argparse, pickle, time
# Repo root for the system CACHE (results/truth/systems). Same resolution as
# topo_config.ROOT: SAILIR_ROOT > the production path if it exists on this box
# > the repo this file lives in. Note SAILIR_NO_SYSTEM_CACHE=1 does NOT avoid
# needing a writable root -- _sys_path() os.makedirs unconditionally, and
# build_system calls it before the flag is ever consulted.
_LEGACY_ROOT = "/het/p4/dshih/jet_images-deep_learning/SAILIR_phase2"
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT = os.environ.get('SAILIR_ROOT') or (
    _LEGACY_ROOT if os.path.isdir(_LEGACY_ROOT) else _REPO_ROOT)
sys.path.insert(0, ROOT); sys.path.insert(0, os.path.join(ROOT, "reduction"))

from sailir import ibp_env
from sailir.topology import Topology
import topo_config as _tc

# The field the whole elimination runs in. Configurable because a prime change
# is NOT a config change downstream: mod-p coefficients cannot be converted
# between coprime moduli (c mod 1009 carries no information about c mod 101), so
# any corpus is tied to the prime it was generated under, and the model's
# nn.Embedding(prime, ...) row count is baked into its checkpoint. Default 1009
# keeps every existing run bit-identical.
P = int(os.environ.get('SAILIR_PRIME', '1009'))

# Per-rung seed budget for the escalation ladder. A rung whose projected
# seed count exceeds this is SKIPPED without building its system. Default
# 25000 preserves historical behaviour exactly; the dots-only corpus never
# exceeded it, but real g1023 targets (r=8-11) blow past it on rung ONE.
_SEED_BUDGET = int(os.environ.get('SAILIR_SEED_BUDGET', '25000'))


def rs_of(t):
    return (sum(x for x in t if x > 0), sum(-x for x in t if x < 0))


def sector_of(t):
    m = 0
    for i in range(_tc.N_DEN):
        if t[i] > 0:
            m |= 1 << i
    return m


class TruthEngine:
    def __init__(self, topology_dir, trivial_path=None):
        self.topo = Topology.from_dir(topology_dir)
        ibp_env.init_from_topology(self.topo)
        ibp_env.set_prime(P)
        ibp_env.set_paper_masters_only(True)
        if os.environ.get('SAILIR_SECTOR_RANK', '0') == '1':
            from canonical_masters import apply_canonical_masters
            apply_canonical_masters()
        from symmetry_route import tkey
        self.tkey = tkey
        self.env = ibp_env.IBPEnvironment()
        self.n_actions = self.topo.n_actions
        self.systems = {}          # (sector, rmax, smax) -> rules
        self.trivial = set()
        if trivial_path and os.path.exists(trivial_path):
            self.trivial = set(int(x) for x in
                               open(trivial_path).read().strip().split(","))

    # ---- sector system -----------------------------------------------------
    def _seeds(self, S, rmax, smax):
        """In-sector seeds: present dens >= 1 (dots distribute r-L extra),
        numerator powers on the non-present slots (absent dens + ISPs)."""
        dens = [i for i in range(_tc.N_DEN) if S >> i & 1]
        nums = [i for i in range(_tc.N_IND) if i not in dens]
        L = len(dens)

        def distribute(total, slots):
            if not slots:
                if total == 0:
                    yield {}
                return
            first, rest = slots[0], slots[1:]
            for k in range(total + 1):
                for d in distribute(total - k, rest):
                    if k:
                        d = dict(d); d[first] = k
                    yield d

        for extra in range(0, rmax - L + 1):
            for dots in distribute(extra, dens):
                for s in range(0, smax + 1):
                    for negs in distribute(s, nums):
                        t = [0] * _tc.N_IND
                        for i in dens:
                            t[i] = 1 + dots.get(i, 0)
                        for i, k in negs.items():
                            t[i] = -k
                        yield tuple(t)

    def _sys_path(self, S, rmax, smax):
        d = os.path.join(ROOT, "results/truth/systems")
        os.makedirs(d, exist_ok=True)
        # sys2: rules carry their substitution DEPENDENCIES (4-tuples) — needed
        # to reconstruct worker-form action sequences
        return os.path.join(d, f"sys2_{_tc.TOPOLOGY}_S{S}_r{rmax}_s{smax}.pkl")

    def build_system(self, S, rmax, smax, verbose=True):
        key = (S, rmax, smax)
        if key in self.systems:
            return self.systems[key]
        path = self._sys_path(S, rmax, smax)
        if os.path.exists(path):
            with open(path, "rb") as f:
                self.systems[key] = pickle.load(f)
            if verbose:
                print(f"  [system S={S} r<={rmax} s<={smax}] loaded "
                      f"({len(self.systems[key])} rules)", flush=True)
            return self.systems[key]
        from sailir.ibp_env import get_raw_equation
        t0 = time.time()
        # pass 1: SORT KEYS ONLY (max integral per equation; lowest max first
        # so low equations become rules before higher ones are reduced). The
        # equations themselves are REGENERATED in pass 2 — a microsecond-scale
        # template evaluation each — instead of holding 100k+ term dicts in
        # memory for the whole build. Trade: one extra raw generation per
        # equation; win: roughly halves the build's peak memory.
        keyed = []
        n_seed = 0
        for seed in self._seeds(S, rmax, smax):
            n_seed += 1
            for op in range(self.n_actions):
                eq = get_raw_equation(self.env.ibp_t, self.env.li_t, op, seed)
                if eq:
                    piv = min(eq, key=self.tkey)     # smallest tkey = highest
                    keyed.append((self.tkey(piv), op, seed))
        keyed.sort(key=lambda x: x[0], reverse=True)
        rules = {}
        n_master_piv = 0

        def reduce_full(eq, deps=None):
            out = dict(eq)
            while True:
                sub = None
                for J in out:
                    if J in rules:
                        if sub is None or self.tkey(J) < self.tkey(sub):
                            sub = J
                if sub is None:
                    return out
                if deps is not None:
                    deps.add(sub)
                co = out.pop(sub)
                for K, cK in rules[sub][0].items():
                    v = (out.get(K, 0) + co * cK) % P
                    if v:
                        out[K] = v
                    else:
                        out.pop(K, None)

        n_eqs = len(keyed)
        for _, op, seed in keyed:
            eq = get_raw_equation(self.env.ibp_t, self.env.li_t, op, seed)
            deps = set()
            red = reduce_full(eq, deps)
            if not red:
                continue
            piv = min(red, key=self.tkey)
            if sector_of(piv) != S:
                continue                        # all-subsector equation: park
            if ibp_env.is_master(piv):
                n_master_piv += 1               # skipped, see docstring
                continue
            co = red.pop(piv)
            inv = pow(co, P - 2, P)
            tail = {K: (-v * inv) % P for K, v in red.items() if v % P}
            rules[piv] = (tail, op, seed, frozenset(deps))
        if verbose:
            print(f"  [system S={S} r<={rmax} s<={smax}] seeds={n_seed} "
                  f"eqs={n_eqs} rules={len(rules)} "
                  f"master-pivot-skipped={n_master_piv} ({time.time()-t0:.1f}s)",
                  flush=True)
        self.systems[key] = rules
        # SAILIR_NO_SYSTEM_CACHE=1: skip persistence. A single system runs
        # 269 MB - 1.47 GB on disk and the 18k-target corpus needs 2,317
        # distinct ones (up to 2.3 TB) on a filesystem already at 91%. When
        # targets are BATCHED BY SYSTEM the on-disk cache buys nothing anyway:
        # the group builds its system once in RAM and reuses it in-process.
        if os.environ.get('SAILIR_NO_SYSTEM_CACHE', '0') != '1':
            with open(path, "wb") as f:
                pickle.dump(rules, f)
        return rules

    # ---- targeted local rule construction ---------------------------------
    def build_rule_for(self, J, rules, max_dist=3, verbose=True):
        """Find a rule for one specific unruled integral J: generate equations
        from seeds within L1 distance <= d of J (in-sector), reduce them
        against the EXISTING rule set, and take one whose reduced pivot is
        exactly J. Cheap and local — avoids whole-box cap escalation (a
        single-pass Laporta leaves occasional interior coverage holes; J may
        simply never have become anyone's pivot)."""
        from sailir.ibp_env import get_raw_equation
        S = sector_of(J)
        dens = [i for i in range(_tc.N_DEN) if S >> i & 1]
        nums = [i for i in range(_tc.N_IND) if i not in dens]

        def reduce_full(eq, deps):
            out = dict(eq)
            while True:
                sub = None
                for K in out:
                    if K in rules:
                        if sub is None or self.tkey(K) < self.tkey(sub):
                            sub = K
                if sub is None:
                    return out
                deps.add(sub)
                co = out.pop(sub)
                for K, cK in rules[sub][0].items():
                    v = (out.get(K, 0) + co * cK) % P
                    if v:
                        out[K] = v
                    else:
                        out.pop(K, None)

        def near_seeds(d):
            """In-sector seeds with L1 distance <= d from J (dens can go up,
            numerator slots can deepen or relax toward 0)."""
            def rec(slots, budget, cur):
                if not slots:
                    yield tuple(cur)
                    return
                i, rest = slots[0], slots[1:]
                lo = -budget if i in nums else max(1 - J[i], -budget)
                for delta in range(lo, budget + 1):
                    v = J[i] + delta
                    if i in dens and v < 1:
                        continue
                    if i in nums and v > 0:
                        continue
                    cur.append(v)
                    yield from rec(rest, budget - abs(delta), cur)
                    cur.pop()
            yield from rec(list(range(_tc.N_IND)), d, [])

        for d in range(1, max_dist + 1):
            for seed in near_seeds(d):
                for op in range(self.n_actions):
                    eq = get_raw_equation(self.env.ibp_t, self.env.li_t, op, seed)
                    if not eq or J not in eq:
                        continue
                    deps = set()
                    red = reduce_full(eq, deps)
                    if not red:
                        continue
                    piv = min(red, key=self.tkey)
                    if piv != J:
                        continue
                    co = red.pop(piv)
                    inv = pow(co, P - 2, P)
                    tail = {K: (-v * inv) % P for K, v in red.items() if v % P}
                    rules[J] = (tail, op, seed, frozenset(deps))
                    if verbose:
                        print(f"  [local rule] {list(J)} via op={op} "
                              f"seed-dist={d}", flush=True)
                    return True
        return False

    # ---- replay ------------------------------------------------------------
    def reduce(self, T, dr=1, ds=1, record_states=False, max_steps=200000,
               recorder=None):
        """Full truth reduction of T to masters. Returns dict with final_expr,
        trajectory [(pivot, op, delta)], stats. record_states=True additionally
        snapshots the expression before every step — MEMORY-HEAVY (GBs on long
        replays); default off, states are exactly reconstructable by replaying
        the trajectory against the persisted systems.

        recorder: optional callback invoked BEFORE each substitution as
        recorder(step, J, op, seed, tail, expr) — used by
        truth_record_training.py to emit training samples; must not mutate
        expr."""
        T = tuple(T)
        expr = {T: 1 % P}
        traj = []
        states = []
        caps = {}                  # sector -> (rmax, smax) in use
        t0 = time.time()
        for step in range(max_steps):
            nm = [J for J in expr if not ibp_env.is_master(J)
                  and sector_of(J) != 0]
            # drop trivial (scaleless) sector terms: exactly Kira's list
            dead = [J for J in nm if sector_of(J) in self.trivial]
            for J in dead:
                expr.pop(J)
            nm = [J for J in nm if sector_of(J) not in self.trivial]
            if not nm:
                break
            J = min(nm, key=self.tkey)          # highest in the total order
            S = sector_of(J)
            r, s = rs_of(J)
            want = (max(r + dr, caps.get(S, (0, 0))[0]),
                    max(s + ds, caps.get(S, (0, 0))[1]))
            rules = self.build_system(S, *want)
            caps[S] = want
            if J not in rules:
                # targeted local construction first (interior coverage holes
                # of single-pass Laporta), then ADAPTIVE cap escalation while
                # the projected system stays cheap (small sectors cost seconds
                # — sector-cone corners often need surprisingly deep seeds).
                ok = self.build_rule_for(J, rules)
                tries = 0
                while not ok and tries < 3:
                    nxt = (want[0] + 1, want[1] + 1)
                    est = sum(1 for _ in self._seeds(S, *nxt))
                    if est > 25000:
                        break
                    rules = self.build_system(S, *nxt)
                    caps[S] = want = nxt
                    ok = J in rules or self.build_rule_for(J, rules)
                    tries += 1
                if not ok and J not in rules:
                    raise RuntimeError(
                        f"no rule for {list(J)} (sector {S}) at caps {want} "
                        f"+ local search (next escalation too large) — "
                        f"raise --dr/--ds")
            tail, op, seed = rules[J][:3]
            if record_states:
                states.append(dict(expr))
            if recorder is not None:
                recorder(step, J, op, seed, tail, expr, rules)
            traj.append((J, op, tuple(x - y for x, y in zip(seed, J))))
            co = expr.pop(J)
            for K, cK in tail.items():
                v = (expr.get(K, 0) + co * cK) % P
                if v:
                    expr[K] = v
                else:
                    expr.pop(K, None)
        else:
            raise RuntimeError("max_steps exceeded")
        return dict(final_expr=expr, trajectory=traj, states=states,
                    caps=caps, steps=len(traj), time=time.time() - t0)


    # ---- worker-semantics ground-truth ACTION SEQUENCE --------------------
    def worker_replay(self, T, dr=1, ds=1, verbose=True):
        """The ground-truth ONE-STEP action sequence in worker-exact form.

        A rule's pivot need not appear in its generator's RAW equation — it
        can be exposed only after other rules are substituted (that is how
        the elimination built it). The worker mirrors this with its
        accumulated substitution store: an action (target, op, delta) is
        valid when the raw equation, AFTER substituting all previously solved
        targets, contains the target. So the truth sequence is the DEPENDENCY
        CLOSURE of T's rule, emitted dependencies-first (each rule recorded
        the pivots substituted while it was built): every emitted action
        solves its pivot from (raw equation + prior solves) and joins the
        substitution store; T's own action comes last and collapses the
        active expression {T} into strictly-lower terms — the production
        success criterion fires immediately.

        Returns dict(actions=[(pivot, op, delta), ...] in application order,
        sol_store={pivot: solved tail} as the worker would hold them,
        result_expr=the one-step reduction of T (all strictly lower), steps).
        """
        from sailir.ibp_env import get_raw_equation
        T = tuple(T)
        S = sector_of(T)
        r, s = rs_of(T)
        # escalation ladder, ASYMMETRIC: corners typically need deep DOTS
        # (the classic route to a sector-bottom collapse), while the numerator
        # direction explodes the seed count — push r hard, s gently. Each
        # rung is skipped if its projected seed count exceeds the budget.
        rules = None
        # dots-first ladder: pure-dot deepening (b fixed) grows slowly for
        # small sectors and is the classic route to corner collapses — the
        # Kira nosym master list proves these corners ARE IBP+LI-reducible,
        # so depth, not different information, is what's needed.
        for (a, b) in [(dr, ds), (dr + 1, ds), (dr + 2, ds), (dr + 3, ds),
                       (dr + 4, ds), (dr + 5, ds), (dr + 1, ds + 1),
                       (dr + 2, ds + 1), (dr + 3, ds + 1)]:
            if sum(1 for _ in self._seeds(S, r + a, s + b)) > _SEED_BUDGET:
                continue
            # Evict prior rungs to keep peak memory at ONE system. With
            # SAILIR_KEEP_SYSTEMS=1 the in-memory cache is retained instead,
            # so a batch of targets SHARING a system builds it once rather
            # than once per target -- the whole point of grouping. Safe only
            # because a group's targets resolve to the same rung; memory stays
            # ~one system (measured ~4 GB at 36-54k seeds).
            if os.environ.get('SAILIR_KEEP_SYSTEMS', '0') != '1':
                self.systems.clear()
            rules = self.build_system(S, r + a, s + b, verbose=verbose)
            if T in rules or self.build_rule_for(T, rules):
                break
        else:
            # Distinguish the two failure modes: a ladder that was explored and
            # came up empty needs more DEPTH, but a ladder whose every rung was
            # rejected by the seed budget was never explored at all, and raising
            # --dr/--ds there changes nothing (deeper rungs have MORE seeds).
            _n = [(a, b, sum(1 for _ in self._seeds(S, r + a, s + b)))
                  for (a, b) in [(dr, ds), (dr + 1, ds), (dr + 2, ds),
                                 (dr + 3, ds), (dr + 4, ds), (dr + 5, ds),
                                 (dr + 1, ds + 1), (dr + 2, ds + 1),
                                 (dr + 3, ds + 1)]]
            _over = [x for x in _n if x[2] > _SEED_BUDGET]
            if len(_over) == len(_n):
                raise RuntimeError(
                    f"no rule for target {list(T)}: ALL {len(_n)} ladder rungs "
                    f"were skipped by the seed budget {_SEED_BUDGET:,} "
                    f"(cheapest rung needs {min(x[2] for x in _n):,} seeds at "
                    f"r={r}+{_n[0][0]} s={s}+{_n[0][1]}). build_system was never "
                    f"called. Raise SAILIR_SEED_BUDGET — raising --dr/--ds "
                    f"cannot help, deeper rungs need MORE seeds.")
            raise RuntimeError(f"no rule for target {list(T)} within the "
                               f"escalation ladder ({len(_over)}/{len(_n)} rungs "
                               f"skipped by seed budget {_SEED_BUDGET:,}) — "
                               f"raise --dr/--ds")

        # dependencies-first emission order (iterative postorder over the
        # recorded dependency sets; acyclic by construction: a rule only ever
        # substituted rules created before it)
        order = []
        done = set()
        stack = [(T, False)]
        while stack:
            J, expanded = stack.pop()
            if J in done:
                continue
            if expanded:
                done.add(J)
                order.append(J)
                continue
            stack.append((J, True))
            for D in sorted(rules[J][3], key=self.tkey):
                if D not in done:
                    assert D in rules, "dependency without a rule"
                    stack.append((D, False))

        subs = {}
        actions = []
        for J in order:
            _, op, seed, _ = rules[J]
            raw = get_raw_equation(self.env.ibp_t, self.env.li_t, op, seed)
            # worker semantics: substitute all prior solves, then solve for J
            cached = dict(raw)
            while True:
                hit = next((K for K in cached if K in subs), None)
                if hit is None:
                    break
                co = cached.pop(hit)
                for K, cK in subs[hit].items():
                    v = (cached.get(K, 0) + co * cK) % P
                    if v:
                        cached[K] = v
                    else:
                        cached.pop(K, None)
            assert J in cached and cached[J] % P, \
                f"action for {list(J)} invalid: pivot absent after substitution"
            inv = pow(cached.pop(J), P - 2, P)
            subs[J] = {K: (-c * inv) % P for K, c in cached.items() if c % P}
            actions.append((J, op, tuple(x - y for x, y in zip(seed, J))))
        result = dict(subs[T])
        kT = self.tkey(T)
        assert all(self.tkey(K) > kT for K in result), \
            "one-step result contains terms at-or-above the target"
        if verbose:
            print(f"  [worker_replay] {len(actions)} actions "
                  f"(dependency closure of the target rule); result "
                  f"{len(result)} strictly-lower terms", flush=True)
        return dict(actions=actions, sol_store=subs, result_expr=result,
                    steps=len(actions))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--integral', required=True)
    ap.add_argument('--output', required=True)
    ap.add_argument('--dr', type=int, default=1)
    ap.add_argument('--ds', type=int, default=1)
    ap.add_argument('--trivialsector', default=None,
                    help='Kira trivialsector file (comma-separated ids)')
    ap.add_argument('--one-step-actions', action='store_true',
                    help='produce the worker-semantics ground-truth ACTION '
                         'SEQUENCE for the ONE-STEP reduction of the target '
                         '(no full reduction to masters)')
    args = ap.parse_args()
    T = tuple(int(x) for x in args.integral.strip("'\"").split(","))
    eng = TruthEngine(_tc.TOPO_DIR, args.trivialsector)
    if args.one_step_actions:
        out = eng.worker_replay(T, dr=args.dr, ds=args.ds)
        n_pass = len(out['result_expr'])
        print(f"ONE-STEP TRUTH SEQUENCE: {out['steps']} actions; result = "
              f"{n_pass} strictly-lower terms (passenger expansion)")
        for i, (J, op, delta) in enumerate(out['actions'][:10]):
            print(f"   step {i}: eliminate {list(J)} via op={op} delta={list(delta)}")
        if out['steps'] > 10:
            print(f"   ... ({out['steps'] - 10} more)")
    else:
        out = eng.reduce(T, dr=args.dr, ds=args.ds)
        print(f"TRUTH REDUCTION: {out['steps']} steps, {out['time']:.1f}s, "
              f"{len(out['final_expr'])} master terms")
        for k, v in sorted(out['final_expr'].items()):
            print(f"   {v:>4} * {list(k)}")
    with open(args.output, "wb") as f:
        pickle.dump(out, f)
    print(f"saved -> {args.output}")


if __name__ == "__main__":
    main()
